### ISSUE TITLE
DB Schema

### ISSUE THREAD

**Issue by brookeangel** [kattelles/Stumblr#3]
* Do blogs have a cover photo url in the schema?
* Don't need follows and followings - just follows with a blog_id and user_id?
* Reblogs need a table - I might keep them as a bonus feature. They are actually kind of tricky to implement.

**Comment by kattelles** [comment]
1. I added profile pic as an optional column in the blog table 
2. got rid of followings, only have follow table now 
3. leaving reblogs as a bonus feature :)
